package net.minecraft.util.registry;

import com.mojang.serialization.Codec;
import net.minecraft.block.Block;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.ai.brain.Activity;
import net.minecraft.entity.ai.brain.MemoryModuleType;
import net.minecraft.entity.ai.brain.Schedule;
import net.minecraft.entity.ai.brain.sensor.SensorType;
import net.minecraft.entity.attribute.EntityAttribute;
import net.minecraft.entity.decoration.painting.PaintingMotive;
import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.fluid.Fluid;
import net.minecraft.item.Item;
import net.minecraft.loot.condition.LootConditionType;
import net.minecraft.loot.entry.LootPoolEntryType;
import net.minecraft.loot.function.LootFunctionType;
import net.minecraft.loot.provider.nbt.LootNbtProviderType;
import net.minecraft.loot.provider.number.LootNumberProviderType;
import net.minecraft.loot.provider.score.LootScoreProviderType;
import net.minecraft.particle.ParticleType;
import net.minecraft.potion.Potion;
import net.minecraft.recipe.RecipeSerializer;
import net.minecraft.recipe.RecipeType;
import net.minecraft.screen.ScreenHandlerType;
import net.minecraft.sound.SoundEvent;
import net.minecraft.stat.StatType;
import net.minecraft.structure.StructurePieceType;
import net.minecraft.structure.StructureSet;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElementType;
import net.minecraft.structure.processor.StructureProcessorList;
import net.minecraft.structure.processor.StructureProcessorType;
import net.minecraft.structure.rule.PosRuleTestType;
import net.minecraft.structure.rule.RuleTestType;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.floatprovider.FloatProviderType;
import net.minecraft.util.math.intprovider.IntProviderType;
import net.minecraft.util.math.noise.DoublePerlinNoiseSampler;
import net.minecraft.village.VillagerProfession;
import net.minecraft.village.VillagerType;
import net.minecraft.world.World;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.source.BiomeSource;
import net.minecraft.world.chunk.ChunkStatus;
import net.minecraft.world.dimension.DimensionOptions;
import net.minecraft.world.dimension.DimensionType;
import net.minecraft.world.event.GameEvent;
import net.minecraft.world.event.PositionSourceType;
import net.minecraft.world.gen.blockpredicate.BlockPredicateType;
import net.minecraft.world.gen.carver.Carver;
import net.minecraft.world.gen.carver.ConfiguredCarver;
import net.minecraft.world.gen.chunk.ChunkGenerator;
import net.minecraft.world.gen.chunk.ChunkGeneratorSettings;
import net.minecraft.world.gen.chunk.placement.StructurePlacementType;
import net.minecraft.world.gen.densityfunction.DensityFunction;
import net.minecraft.world.gen.feature.*;
import net.minecraft.world.gen.feature.size.FeatureSizeType;
import net.minecraft.world.gen.foliage.FoliagePlacerType;
import net.minecraft.world.gen.heightprovider.HeightProviderType;
import net.minecraft.world.gen.placementmodifier.PlacementModifierType;
import net.minecraft.world.gen.stateprovider.BlockStateProviderType;
import net.minecraft.world.gen.surfacebuilder.MaterialRules;
import net.minecraft.world.gen.treedecorator.TreeDecoratorType;
import net.minecraft.world.gen.trunk.TrunkPlacerType;
import net.minecraft.world.poi.PointOfInterestType;

/* Backport for net.minecraft.util.registry.RegistryKeys from 22w45a
 *
 * Added for easier code change across versions
 */
public class RegistryKeys
{
    public static final RegistryKey<Registry<SoundEvent>> SOUND_EVENT = Registry.SOUND_EVENT_KEY;
    public static final RegistryKey<Registry<Fluid>> FLUID = Registry.FLUID_KEY;
    public static final RegistryKey<Registry<StatusEffect>> MOB_EFFECT = Registry.MOB_EFFECT_KEY;
    public static final RegistryKey<Registry<Block>> BLOCK = Registry.BLOCK_KEY;
    public static final RegistryKey<Registry<Enchantment>> ENCHANTMENT = Registry.ENCHANTMENT_KEY;
    public static final RegistryKey<Registry<EntityType<?>>> ENTITY_TYPE = Registry.ENTITY_TYPE_KEY;
    public static final RegistryKey<Registry<Item>> ITEM = Registry.ITEM_KEY;
    public static final RegistryKey<Registry<Potion>> POTION = Registry.POTION_KEY;
    public static final RegistryKey<Registry<ParticleType<?>>> PARTICLE_TYPE = Registry.PARTICLE_TYPE_KEY;
    public static final RegistryKey<Registry<BlockEntityType<?>>> BLOCK_ENTITY_TYPE = Registry.BLOCK_ENTITY_TYPE_KEY;
    public static final RegistryKey<Registry<PaintingMotive>> MOTIVE = Registry.MOTIVE_KEY;
    public static final RegistryKey<Registry<Identifier>> CUSTOM_STAT = Registry.CUSTOM_STAT_KEY;
    public static final RegistryKey<Registry<ChunkStatus>> CHUNK_STATUS = Registry.CHUNK_STATUS_KEY;
    public static final RegistryKey<Registry<RuleTestType<?>>> RULE_TEST = Registry.RULE_TEST_KEY;
    public static final RegistryKey<Registry<PosRuleTestType<?>>> POS_RULE_TEST = Registry.POS_RULE_TEST_KEY;
    public static final RegistryKey<Registry<ScreenHandlerType<?>>> MENU = Registry.MENU_KEY;
    public static final RegistryKey<Registry<RecipeType<?>>> RECIPE_TYPE = Registry.RECIPE_TYPE_KEY;
    public static final RegistryKey<Registry<RecipeSerializer<?>>> RECIPE_SERIALIZER = Registry.RECIPE_SERIALIZER_KEY;
    public static final RegistryKey<Registry<EntityAttribute>> ATTRIBUTE = Registry.ATTRIBUTE_KEY;
    public static final RegistryKey<Registry<GameEvent>> GAME_EVENT = Registry.GAME_EVENT_KEY;
    public static final RegistryKey<Registry<PositionSourceType<?>>> POSITION_SOURCE_TYPE = Registry.POSITION_SOURCE_TYPE_KEY;
    public static final RegistryKey<Registry<StatType<?>>> STAT_TYPE = Registry.STAT_TYPE_KEY;
    public static final RegistryKey<Registry<VillagerType>> VILLAGER_TYPE = Registry.VILLAGER_TYPE_KEY;
    public static final RegistryKey<Registry<VillagerProfession>> VILLAGER_PROFESSION = Registry.VILLAGER_PROFESSION_KEY;
    public static final RegistryKey<Registry<PointOfInterestType>> POINT_OF_INTEREST_TYPE = Registry.POINT_OF_INTEREST_TYPE_KEY;
    public static final RegistryKey<Registry<MemoryModuleType<?>>> MEMORY_MODULE_TYPE = Registry.MEMORY_MODULE_TYPE_KEY;
    public static final RegistryKey<Registry<SensorType<?>>> SENSOR_TYPE = Registry.SENSOR_TYPE_KEY;
    public static final RegistryKey<Registry<Schedule>> SCHEDULE = Registry.SCHEDULE_KEY;
    public static final RegistryKey<Registry<Activity>> ACTIVITY = Registry.ACTIVITY_KEY;
    public static final RegistryKey<Registry<LootPoolEntryType>> LOOT_POOL_ENTRY_TYPE = Registry.LOOT_POOL_ENTRY_TYPE_KEY;
    public static final RegistryKey<Registry<LootFunctionType>> LOOT_FUNCTION_TYPE = Registry.LOOT_FUNCTION_TYPE_KEY;
    public static final RegistryKey<Registry<LootConditionType>> LOOT_CONDITION_TYPE = Registry.LOOT_CONDITION_TYPE_KEY;
    public static final RegistryKey<Registry<LootNumberProviderType>> LOOT_NUMBER_PROVIDER_TYPE = Registry.LOOT_NUMBER_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<LootNbtProviderType>> LOOT_NBT_PROVIDER_TYPE = Registry.LOOT_NBT_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<LootScoreProviderType>> LOOT_SCORE_PROVIDER_TYPE = Registry.LOOT_SCORE_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<DimensionType>> DIMENSION_TYPE = Registry.DIMENSION_TYPE_KEY;
    public static final RegistryKey<Registry<World>> WORLD = Registry.WORLD_KEY;
    public static final RegistryKey<Registry<DimensionOptions>> DIMENSION = Registry.DIMENSION_KEY;
    public static final RegistryKey<Registry<FloatProviderType<?>>> FLOAT_PROVIDER_TYPE = Registry.FLOAT_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<IntProviderType<?>>> INT_PROVIDER_TYPE = Registry.INT_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<HeightProviderType<?>>> HEIGHT_PROVIDER_TYPE = Registry.HEIGHT_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<BlockPredicateType<?>>> BLOCK_PREDICATE_TYPE = Registry.BLOCK_PREDICATE_TYPE_KEY;
    public static final RegistryKey<Registry<ChunkGeneratorSettings>> CHUNK_GENERATOR_SETTINGS = Registry.CHUNK_GENERATOR_SETTINGS_KEY;
    public static final RegistryKey<Registry<ConfiguredCarver<?>>> CONFIGURED_CARVER = Registry.CONFIGURED_CARVER_KEY;
    public static final RegistryKey<Registry<ConfiguredFeature<?, ?>>> CONFIGURED_FEATURE = Registry.CONFIGURED_FEATURE_KEY;
    public static final RegistryKey<Registry<PlacedFeature>> PLACED_FEATURE = Registry.PLACED_FEATURE_KEY;
    public static final RegistryKey<Registry<ConfiguredStructureFeature<?, ?>>> CONFIGURED_STRUCTURE_FEATURE = Registry.CONFIGURED_STRUCTURE_FEATURE_KEY;
    public static final RegistryKey<Registry<StructureSet>> STRUCTURE_SET = Registry.STRUCTURE_SET_KEY;
    public static final RegistryKey<Registry<StructureProcessorList>> STRUCTURE_PROCESSOR_LIST = Registry.STRUCTURE_PROCESSOR_LIST_KEY;
    public static final RegistryKey<Registry<StructurePool>> STRUCTURE_POOL = Registry.STRUCTURE_POOL_KEY;
    public static final RegistryKey<Registry<Biome>> BIOME = Registry.BIOME_KEY;
    public static final RegistryKey<Registry<DoublePerlinNoiseSampler.NoiseParameters>> NOISE_WORLDGEN = Registry.NOISE_WORLDGEN;
    public static final RegistryKey<Registry<DensityFunction>> DENSITY_FUNCTION = Registry.DENSITY_FUNCTION_KEY;
    public static final RegistryKey<Registry<Carver<?>>> CARVER = Registry.CARVER_KEY;
    public static final RegistryKey<Registry<Feature<?>>> FEATURE = Registry.FEATURE_KEY;
    public static final RegistryKey<Registry<StructureFeature<?>>> STRUCTURE_FEATURE = Registry.STRUCTURE_FEATURE_KEY;
    public static final RegistryKey<Registry<StructurePlacementType<?>>> STRUCTURE_PLACEMENT = Registry.STRUCTURE_PLACEMENT_KEY;
    public static final RegistryKey<Registry<StructurePieceType>> STRUCTURE_PIECE = Registry.STRUCTURE_PIECE_KEY;
    public static final RegistryKey<Registry<PlacementModifierType<?>>> PLACEMENT_MODIFIER_TYPE = Registry.PLACEMENT_MODIFIER_TYPE_KEY;
    public static final RegistryKey<Registry<BlockStateProviderType<?>>> BLOCK_STATE_PROVIDER_TYPE = Registry.BLOCK_STATE_PROVIDER_TYPE_KEY;
    public static final RegistryKey<Registry<FoliagePlacerType<?>>> FOLIAGE_PLACER_TYPE = Registry.FOLIAGE_PLACER_TYPE_KEY;
    public static final RegistryKey<Registry<TrunkPlacerType<?>>> TRUNK_PLACER_TYPE = Registry.TRUNK_PLACER_TYPE_KEY;
    public static final RegistryKey<Registry<TreeDecoratorType<?>>> TREE_DECORATOR_TYPE = Registry.TREE_DECORATOR_TYPE_KEY;
    public static final RegistryKey<Registry<FeatureSizeType<?>>> FEATURE_SIZE_TYPE = Registry.FEATURE_SIZE_TYPE_KEY;
    public static final RegistryKey<Registry<Codec<? extends BiomeSource>>> BIOME_SOURCE = Registry.BIOME_SOURCE_KEY;
    public static final RegistryKey<Registry<Codec<? extends ChunkGenerator>>> CHUNK_GENERATOR = Registry.CHUNK_GENERATOR_KEY;
    public static final RegistryKey<Registry<Codec<? extends MaterialRules.MaterialCondition>>> MATERIAL_CONDITION = Registry.MATERIAL_CONDITION_KEY;
    public static final RegistryKey<Registry<Codec<? extends MaterialRules.MaterialRule>>> MATERIAL_RULE = Registry.MATERIAL_RULE_KEY;
    public static final RegistryKey<Registry<Codec<? extends DensityFunction>>> DENSITY_FUNCTION_TYPE = Registry.DENSITY_FUNCTION_TYPE_KEY;
    public static final RegistryKey<Registry<StructureProcessorType<?>>> STRUCTURE_PROCESSOR = Registry.STRUCTURE_PROCESSOR_KEY;
    public static final RegistryKey<Registry<StructurePoolElementType<?>>> STRUCTURE_POOL_ELEMENT = Registry.STRUCTURE_POOL_ELEMENT_KEY;
}